---
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install pre-commit
        run: pip install pre-commit

      - name: cache pre-commit hooks
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          path: ~/.cache/pre-commit

      - name: Pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure
